on: [push]
name: build
jobs:
  runhaskell:
    name: Build & test uri-templater
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - version: '9.6.7'
            stack-yaml: 'stack-ghc-9.6.yaml'
          - version: '9.8.4'
            stack-yaml: 'stack-ghc-9.8.yaml'
          - version: '9.10.3'
            stack-yaml: 'stack-ghc-9.10.yaml'
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc.version }}
          enable-stack: true
          stack-version: 'latest'
      - run: stack test --stack-yaml ${{ matrix.ghc.stack-yaml }}