on: [push]
name: build
jobs:
  runhaskell:
    name: Build & test uri-templater
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack-yaml:
          - stack-ghc-9.6.yaml
          - stack-ghc-9.8.yaml
          - stack-ghc-9.10.yaml
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
          stack-no-global: true
      - name: Cache Stack dependencies
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles(matrix.stack-yaml) }}
          restore-keys: |
            ${{ runner.os }}-stack-
      - name: Build and test
        run: stack test --stack-yaml ${{ matrix.stack-yaml }}